"""Optional: refresh responsive previews after adding artwork. Requires Pillow."""
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets' / 'web'
OUT.mkdir(exist_ok=True)

def read_data(name):
    return json.loads((ROOT / name).read_text(encoding='utf-8-sig').split('=', 1)[1].strip().rstrip(';'))

archive = read_data('archive-data.js')
media = read_data('page-media.js')
requests = {}
for person in archive['people'] + archive['factions']:
    for record in [person, *person.get('identities', [])]:
        for item in record.get('gallery', []):
            requests.setdefault(item['detail'], set()).add(1400)
for item in media['scenes'] + media['decor'] + media.get('world', []):
    requests.setdefault(item['detail'], set()).update([960, 1600, 2400])

previews = {}
for source, widths in requests.items():
    with Image.open(ROOT / source) as original:
        variants = []
        for edge in sorted(widths):
            image = original.copy()
            image.thumbnail((edge, edge), Image.Resampling.LANCZOS)
            target = OUT / f'{Path(source).stem}-{edge}.webp'
            if not target.exists() or target.stat().st_mtime < (ROOT / source).stat().st_mtime:
                image.save(target, 'WEBP', quality=84, method=6)
            variants.append({'src':target.relative_to(ROOT).as_posix(), 'width':image.width, 'height':image.height})
        previews[source] = variants

sizes = {}
for path in (ROOT / 'assets').rglob('*.webp'):
    with Image.open(path) as image:
        sizes[path.relative_to(ROOT).as_posix()] = list(image.size)
(ROOT / 'media-sizes.js').write_text(
    '/* Generated by tools/build_assets.py; source artwork is unchanged. */\n'
    + 'window.ALMS_IMAGE_SIZES = ' + json.dumps(sizes, separators=(',', ':')) + ';\n'
    + 'window.ALMS_PREVIEWS = ' + json.dumps(previews, separators=(',', ':')) + ';\n', encoding='utf-8')
print(f'{len(previews)} responsive artwork sets; {len(sizes)} intrinsic image dimensions.')
